use GST_BDD

---PROCEDIMIENTO PARA CARGAR USUARIOS
CREATE PROCEDURE ingreso_usuario(
@nombre VARCHAR(50),
@usuario VARCHAR(50) ,
@contrasena VARCHAR(MAX),
@apellido VARCHAR(50),
@DNI VARCHAR(8),
@Telefono VARCHAR(12),
@correo VARCHAR(256),
@idTipoDeUsuario INT
)
AS 

	IF	@idTipoDeUsuario = 1 AND (SELECT COUNT(*) FROM Usuarios WHERE idTipoDeUsuario = 1) > 0
	BEGIN 
	PRINT 'YA EXISTE USUARIO MASTER '
	END
	IF @idTipoDeUsuario = 1 AND (SELECT COUNT(*) FROM Usuarios WHERE idTipoDeUsuario = 1) = 0
	BEGIN 
	INSERT INTO Usuarios(nombre,usuario,contrasena,apellido,DNI,telefono,correo,idTipoDeUsuario) 
	VALUES (@nombre,@usuario,@contrasena,@apellido,@DNI,@telefono,@correo,@idTipoDeUsuario)
	END
	IF @idTipoDeUsuario = 2 
	BEGIN 
	INSERT INTO Usuarios(nombre,usuario,contrasena,apellido,DNI,telefono,correo,idTipoDeUsuario) 
	VALUES (@nombre,@usuario,@contrasena,@apellido,@DNI,@telefono,@correo,@idTipoDeUsuario)
	END
	IF @idTipoDeUsuario = 3
	BEGIN 
	INSERT INTO Usuarios(nombre,usuario,contrasena,apellido,DNI,telefono,correo,idTipoDeUsuario) 
	VALUES (@nombre,@usuario,@contrasena,@apellido,@DNI,@telefono,@correo,@idTipoDeUsuario)
	END
GO


----CREAR LOGIN
CREATE LOGIN Cristian_Maestro WITH PASSWORD = '1234',
CHECK_POLICY = OFF
-----CREAR USUARIO PARA LOGIN
USE GST_BDD
go
CREATE USER Cristian_Maestro FOR LOGIN Cristian_Maestro
go
-----CREAR UN ROL PARA USER MASTER
CREATE ROLE ROL_USER_MAESTRO
-----ASIGNAR PERMISO A ROL_USER_MASTER
GRANT SELECT,INSERT,DELETE,UPDATE ON Usuarios TO ROL_USER_MAESTRO;
-----PERMISO TIPO USUARIO
GRANT INSERT,DELETE,UPDATE ON TiposDeUsuario TO ROL_USER_MAESTRO;
-----ASIGNAR PROCEDIMIENTO DE INSERCION DE USUARIO
GRANT EXECUTE ON ingreso_usuario TO ROL_USER_MAESTRO
-----ASIGNAR ROL 
ALTER ROLE ROL_USER_MAESTRO ADD MEMBER Cristian_Maestro;

--------------------------------
---EJECUCION DE PROCEDIMIENTO

EXECUTE ingreso_usuario 
@nombre = 'juan', 
@usuario = 'juan33', 
@contrasena = '12345',
@apellido = 'rojas' ,
@DNI = '444333222' ,
@telefono = '3756548392' ,
@correo = 'juan33@gmail.com' ,
@idTipoDeUsuario = 2



---CREAR LOGIN
CREATE LOGIN Fabian_Admin WITH PASSWORD = '1234',
CHECK_POLICY = OFF
---CREAR USUARIO PARA LOGIN
USE GST_BDD
go
CREATE USER Fabian_Admin FOR LOGIN Fabian_Admin;
go
-----CREAR UN ROL PARA USER ADMIN
CREATE ROLE ROL_USER_ADMINISTRADOR
-----ASIGNAR PERMISO DE ALTA, BAJA A ROL_USER_ADMIN(CLIENTES)
GRANT SELECT,INSERT,DELETE,UPDATE ON clientes TO ROL_USER_ADMINISTRADOR;
-----ASIGNAR PERMISO DE ALTA A ROL_USER_ADMIN(EQUIPOS)
GRANT SELECT,INSERT,UPDATE ON Equipos TO ROL_USER_ADMINISTRADOR;
-----ASIGNAR PERMISO DE ALTA A ROL_USER_ADMIN(PRESUPUESTO)
GRANT SELECT,INSERT,UPDATE ON PresupuestoS TO ROL_USER_ADMINISTRADOR;
---------ASIGNAR PERMISO DE ALTA, BAJA A ROL_USER_ADMIN(REPARACIONES)
GRANT SELECT,INSERT,SELECT,UPDATE ON Reparaciones TO ROL_USER_ADMINISTRADOR;
-----ASIGNAR ROL_USER_ADMIN A USER_ADMIN
ALTER ROLE ROL_USER_ADMINISTRADOR ADD MEMBER Fabian_Admin;



CREATE LOGIN Rodrigo_Tecnico WITH PASSWORD = '1234',
CHECK_POLICY = OFF
---CREAR USUARIO PARA LOGIN
USE GST_BDD
go
CREATE USER Rodrigo_Tecnico FOR LOGIN Rodrigo_Tecnico;
go
---CREAR ROL PARA TECNICO
CREATE ROLE ROL_USER_TECNICO 
---ASIGNAR PERMISOS A ROL_USER_TECNICO(REVISION)
GRANT SELECT,INSERT,DELETE,UPDATE ON Revisiones TO ROL_USER_TECNICO;
---ASIGNAR ROL EN TABLA REPARACIONES (REPARACIONES)
GRANT SELECT,INSERT,DELETE,UPDATE ON Reparaciones TO ROL_USER_TECNICO;
---ASIGNAR ROL_USER_TECNICO A USER_USUARIO
ALTER ROLE ROL_USER_TECNICO ADD MEMBER Rodrigo_Tecnico;
