-----CREAR USUARIO LOGIN PARA USUARIO_LECTURA(DB_DATAREADER)
CREATE LOGIN usuario_lectura WITH PASSWORD = '1234',
CHECK_POLICY = OFF
-----CREAR USUARIO 
USE GST_BDD
go
CREATE USER usuario_lectura FOR LOGIN usuario_lectura 
go
-----OTORGAR PERMISO DE LECTURA A USUARIO_LECTURA EN LA TABLA PROYECTO_BDI (DB_DATAREADER)
ALTER ROLE db_datareader ADD MEMBER usuario_lectura
go
----PRUEBA (SOLAMENTE SELECT SE EJECUTARÁ CON EXITO)
INSERT INTO Marcas VALUES(N'Toshiba')
DELETE FROM Marcas WHERE nombre = 'Toshiba'
SELECT * FROM Marcas WHERE nombre = 'Toshiba'



---------CREAR USUARIO LOGIN PARA ADMIN(DB_OWNER)
CREATE LOGIN usuario_admin WITH PASSWORD = '1234',
CHECK_POLICY = OFF
---------CREAR USUARIO CON PERMISO DE ADMINISTRADOR
USE GST_BDD
go
CREATE USER usuario_admin FOR LOGIN usuario_admin
go
---------OTORGAR PERMISO DE ADMIN
ALTER ROLE db_owner ADD MEMBER usuario_admin
----PRUEBA(TODAS LAS OPERACIONES SE EJECUTAN CON EXITO)
INSERT INTO Marcas VALUES(N'Toshiba')
DELETE FROM Marcas WHERE nombre = 'Toshiba'
SELECT * FROM Marcas WHERE nombre = 'Toshiba'



--------CREAR LOGIN PARA USUARIO QUE PUEDE LEER UNICAMENTE LA TABLA CLIENTES
CREATE LOGIN lector_una_tabla WITH PASSWORD = '1234',
CHECK_POLICY = OFF

-----CREAR USUARIO 
USE GST_BDD
go
CREATE USER lector_una_tabla FOR LOGIN lector_una_tabla
-----CREAR UN ROL PARA LEER UNA SOLA TABLA
CREATE ROLE ROL_LECTURA_TABLA_CLIENTES;
-----ASIGNAR PERMISO DE LECTURA A ROL_LECTURA_TABLA_CLIENTES
GRANT SELECT ON clientes TO ROL_LECTURA_TABLA_CLIENTES;
-----ASIGNAR ROL_LECTURA_TABLA_CLIENTES A lector_una_tabla
ALTER ROLE ROL_LECTURA_TABLA_CLIENTES ADD MEMBER lector_una_tabla;
----PRUEBA(NO SE EJECUTARA CON EXITO NINGUNA SENTENIA, YA QUE EL USUARIO TIENE PERMISO UNICAMENTE PARA LEER LA TABLA CLIENTES)
INSERT INTO Marcas VALUES(N'Toshiba')
DELETE FROM Marcas WHERE nombre = 'Toshiba'
SELECT * FROM Marcas WHERE nombre = 'Toshiba'